FROM registry.redhat.io/rhel8/dotnet-80:8.0

WORKDIR /app

# Switch to root to perform setup
USER root

# Set up permissions and install tools as root
RUN chown 1001:0 /app && mkdir -p /app/tools && chown 1001:0 /app/tools && dotnet tool install --tool-path /app/tools dotnet-dump --version "8.*" && dotnet tool install --tool-path /app/tools dotnet-gcdump --version "8.*" && dotnet tool install --tool-path /app/tools dotnet-trace --version "8.*" && dotnet tool install --tool-path /app/tools dotnet-counters --version "8.*"

# Switch back to the non-root user for the final image
USER 1002

# Set the entrypoint to our new utility
ENTRYPOINT ["/app/pid-finder"]