apiVersion: v1
kind: LimitRange
metadata:
  name: dotnet-limitrange
  namespace: dotnet-memory-leak-app
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: "2Gi"
      default:
        cpu: "1"
        memory: "1Gi"
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"