apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dotnet-memory-leak-dumps
  namespace: dotnet-memory-leak-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi