apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dotnet-app-role
  namespace: dotnet-memory-leak-app
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dotnet-app-rolebinding
  namespace: dotnet-memory-leak-app
subjects:
  - kind: ServiceAccount
    name: dotnet-app-sa
roleRef:
  kind: Role
  name: dotnet-app-role
  apiGroup: rbac.authorization.k8s.io
---
# Removed unnecessary cluster-scoped permissions
# The application only needs namespace-scoped access to pods and services
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: dotnet-scc
allowPrivilegedContainer: false
allowedCapabilities:
  - SYS_PTRACE
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000160000
      max: 1000169999
users:
  - system:serviceaccount:dotnet-memory-leak-app:dotnet-app-sa
---
# Removed privileged SCC binding - use custom SCC instead
# The custom dotnet-scc provides only necessary SYS_PTRACE capability